// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const learnerSidebar = {
  learnerSidebar: [
    'intro',
    {
      type: 'category',
      label: 'QuickStarts',
      items: [
        'quickstarts/personal-to-integral',
        'quickstarts/moral-line-development',
        'quickstarts/amber-to-rational',
        'quickstarts/rational-to-pluralistic',
        'quickstarts/pluralistic-to-integral',
        'quickstarts/self-line-development',
        'quickstarts/state-development',
        'quickstarts/shadow-work',
        'quickstarts/spiritual-line-development',
        'quickstarts/cognitive-line-development',
        'quickstarts/somatic-line-development',
        'quickstarts/interpersonal-line-development',
        'quickstarts/emotional-line-development',
      ],
    },
    {
      type: 'category',
      label: 'Self Line',
      items: [
        'modules/self-line-overview-psychograph',
        'modules/self-line-conventional-conformist-achiever',
        'modules/self-line-postconventional-individualist-strategist',
        'modules/self-line-postautonomous-construct-aware-unitive',
        'modules/self-line-integration-practice',
      ],
    },
    {
      type: 'category',
      label: 'Emotional Line',
      collapsible: true,
      collapsed: false,
      items: [
        'modules/emotional-line-overview-orientation',
        'modules/emotion-regulation-foundations',
        'modules/affect-labelling-somatic-correlation',
        'modules/emotional-intelligence-somatic-line',
        'modules/emotional-appraisal-meaning-making',
        'modules/emotional-granularity',
        'modules/emotional-interpersonal-integration',
      ],
    },
    {
      type: 'category',
      label: 'Interpersonal Line',
      collapsible: true,
      collapsed: false,
      items: [
        'modules/interpersonal-line-overview-orientation',
        'modules/perspective-taking-empathic-accuracy',
        'modules/co-regulation-relational-attunement',
        'modules/relational-repair-conflict-navigation',
        'modules/cross-difference-dialogue-trust-building',
        'modules/emotional-interpersonal-integration',
      ],
    },
    {
      type: 'category',
      label: 'Cognitive Line',
      items: [
        'modules/cognitive-line-overview-orientation',
        'modules/cognitive-line-concrete-to-formal',
        'modules/cognitive-line-postformal-operations',
        'modules/cognitive-line-metasystematic-vision-logic',
        'modules/cognitive-line-practice-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Spiritual Line',
      items: [
        'modules/spiritual-line-overview-orientation',
        'modules/spiritual-line-mythic-to-rational',
        'modules/spiritual-line-conjunctive-universalizing',
        'modules/spiritual-line-post-metaphysical-integral-religion',
        'modules/spiritual-line-shadow-integration',
        'modules/spiritual-line-practice-architecture',
      ],
    },
    {
      type: 'category',
      label: 'Moral Line',
      items: [
        'modules/moral-line-overview-dual-track',
        'modules/moral-line-conventional-reasoning',
        'modules/moral-line-postconventional-reasoning',
        'modules/moral-line-imagination-integral-ethics',
        'modules/moral-line-shadow-moral-injury',
      ],
    },
    {
      type: 'category',
      label: 'Shadow Work',
      items: [
        'modules/shadow-work-foundation',
        'modules/shadow-321-process',
        'modules/shadow-positive-projection',
        'modules/shadow-persona-mask',
        'modules/shadow-in-relationships',
        'modules/shadow-immunity-to-change',
        'modules/shadow-spiritual-bypassing',
        'modules/shadow-collective-cultural',
      ],
    },
    {
      type: 'category',
      label: 'Somatic Line',
      collapsible: true,
      collapsed: false,
      items: [
        'modules/somatic-line-overview',
      ],
    },
    {
      type: 'category',
      label: 'Modules',
      link: {
        type: 'generated-index',
        slug: '/modules',
        title: 'Modules',
        description: 'Browse standalone learning units across the integral curriculum.',
      },
      items: [
        {
          type: 'category',
          label: 'Stage Development',
          collapsible: true,
          collapsed: true,
          items: [
            'modules/amber-mythic-orientation',
            'modules/rational-orange-orientation',
            'modules/cognitive-dissonance-bridge',
            'modules/perspective-taking-capacity',
            'modules/authority-autonomy-transition',
            {
              type: 'category',
              label: 'Rational → Pluralistic',
              collapsible: true,
              collapsed: true,
              items: [
                'modules/late-orange-disillusionment',
                'modules/empathy-perspective-plurality',
                'modules/emotional-intelligence-somatic-line',
                'modules/contextual-ethics-moral-complexity',
                'modules/ecological-systems-consciousness',
                'modules/authentic-dialogue-collaborative-meaning',
                'modules/community-belonging-collective-intelligence',
                'modules/relativism-limits-of-pluralism',
                'modules/pluralistic-green-orientation',
              ],
            },
            {
              type: 'category',
              label: 'Pluralistic → Integral',
              collapsible: true,
              collapsed: true,
              items: [
                'modules/late-green-emergence-signals',
                'modules/integral-teal-orientation',
                'modules/vision-logic-metasystematic-thinking',
                'modules/healthy-hierarchy-actualization-gradient',
                'modules/integral-ethics-beyond-relativism',
                'modules/integral-shadow-teal-trap',
                'modules/multiperspectival-leadership-action',
                'modules/integral-life-practice-embodying-2nd-tier',
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'State Training',
          collapsible: true,
          collapsed: true,
          items: [
            'modules/gross-state-awareness',
            'modules/subtle-state-access',
            'modules/causal-witness-state',
            'modules/nondual-awareness-orientation',
            'modules/flow-peak-experience',
          ],
        },
        {
          type: 'category',
          label: 'Core Skills',
          collapsible: true,
          collapsed: true,
          items: [
            'modules/mindfulness-basics',
            'modules/mindfulness-deepening',
            'modules/cognitive-bias-101',
            'modules/critical-thinking-foundations',
            'modules/evidence-evaluation',
            'modules/systems-thinking-101',
          ],
        },
        {
          type: 'category',
          label: 'Shadow Work',
          collapsible: true,
          collapsed: true,
          items: [
            'modules/shadow-work-foundation',
            'modules/shadow-integration-101',
            'modules/shadow-321-process',
            'modules/shadow-positive-projection',
            {
              type: 'category',
              label: 'Shadow Applications',
              collapsible: true,
              collapsed: true,
              items: [
                'modules/shadow-persona-mask',
                'modules/shadow-in-relationships',
                'modules/shadow-immunity-to-change',
                'modules/shadow-spiritual-bypassing',
                'modules/shadow-collective-cultural',
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Maps',
      items: [
        'maps/glossary',
        'maps/aqal-overview',
        'maps/aqal-glossary',
        'maps/amber-rational-progress-assessment',
        'maps/rational-pluralistic-progress-assessment',
        'maps/pluralistic-integral-progress-assessment',
        'maps/aqal-label-crosswalk',
        'maps/aqal-competency-map',
        'maps/emotional-line-stage-map',
        'maps/ilp-practice-taxonomy',
        'maps/integral-life-practice-integration',
        'maps/cognitive-line-developmental-profile',
        'maps/spiritual-line-developmental-profile',
        'maps/state-identification-assessment',
        'maps/state-stage-integration-map',
        'maps/shadow-developmental-lines-map',
        'maps/shadow-work-self-assessment',
        'maps/moral-line-developmental-profile',
        'maps/self-line-developmental-profile',
      ],
    },
    {
      type: 'category',
      label: 'Reflection',
      items: ['reflections/daily-template'],
    },
    {
      type: 'link',
      label: 'Prototype',
      href: '/prototype',
    },
  ],
};

module.exports = learnerSidebar;